final _countriesCode = const {
  "AE": "United Arab Emirates",
  "AR": "Argentina",
  "AT": "Austria",
  "AU": "Australia",
  "BE": "Belgium",
  "BG": "Bulgaria",
  "BR": "Brazil",
  "CA": "Canada",
  "CH": "Switzerland",
  "CL": "Chile",
  "CO": "Colombia",
  "CR": "Costa Rica",
  "CZ": "Czechia",
  "DE": "Germany",
  "DK": "Denmark",
  "EE": "Estonia",
  "ES": "Spain",
  "FI": "Finland",
  "FR": "France",
  "GR": "Greece",
  "HK": "Hong Kong",
  "HU": "Hungary",
  "IE": "Ireland",
  "IL": "Israel",
  "IN": "India",
  "IS": "Iceland",
  "IT": "Italy",
  "JP": "Japan",
  "KR": "Korea",
  "LT": "Lithuania",
  "LU": "Luxembourg",
  "LV": "Latvia",
  "MD": "Moldova",
  "MX": "Mexico",
  "MY": "Malaysia",
  "NL": "Netherlands",
  "NO": "Norway",
  "NZ": "New Zealand",
  "PE": "Peru",
  "PL": "Poland",
  "PT": "Portugal",
  "RO": "Romania",
  "RS": "Serbia",
  "RU": "Russian Federation",
  "SE": "Sweden",
  "SG": "Singapore",
  "SI": "Slovenia",
  "SK": "Slovakia",
  "TR": "Turkey",
  "TW": "Taiwan",
  "UA": "Ukraine",
  "UK": "United Kingdom",
  "US": "United States",
  "ZA": "South Africa",
};

class CountriesCode {
  static String value(String code) => _countriesCode[code] ?? '';
}
