name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Cache pubspec
      - uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}

      # Setup java for build android
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      # Setup flutter stable version
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      # Install dependencies
      - run: flutter pub get

      # Format code
      - run: flutter format --set-exit-if-changed .

      # Analyze code
      - run: flutter analyze .

      # Run testing
      - run: flutter test

      # Build apk on diferent abi
      - name: Build APK
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: flutter build apk --split-per-abi --dart-define=sentryDsn=$SENTRY_DSN
        if: github.ref == 'refs/heads/main'

      # Upload artifact
      - uses: actions/upload-artifact@v1
        if: github.ref == 'refs/heads/main'
        with:
          name: apks
          path: build/app/outputs/apk/release/
