name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Test and Analyze
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Cache pubspec
      - uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}

      # Setup java for build android
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      # Setup flutter stable version
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      # Install dependencies
      - run: flutter pub get

      # Format code
      - run: flutter format --set-exit-if-changed .

      # Analyze code
      - run: flutter analyze .

      # Run testing
      - run: flutter test

  build:
    name: Build APK and Upload Artifact
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      # Build apk on diferent abi
      - run: flutter build apk --split-per-abi

      # Upload artifact
      - uses: actions/upload-artifact@v1
        with:
          name: apks
          path: build/app/outputs/apk/release/
