on:
  push:
    tags:
    - 'v*'

name: Upload Release Assets

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - run: flutter pub get

      - name: Build APK
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: flutter build apk --split-per-abi --dart-define=sentryDsn=$SENTRY_DSN

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          token: ${{ secrets.TOKEN }}
